"""Replace templated seed-profile copy with distinct content, one batch at a time.

The original seeder reused a small pool: 200 profiles shared 30 bios, 40
headlines and 10 "looking for" lines, so one bio appeared 14 times and one
"looking for" appeared 28 times. Five profiles were called Harry. Scrolling
Discover, the repetition is obvious within about four cards, which is worse
than an empty feed — it reads as a platform padding its numbers.

These are labelled in the UI as example profiles and cannot be liked or
messaged. The point of the rewrite is that a demonstration should look like
the product working, not like a mail merge.

Run per batch so the copy can be reviewed before the next one:

    python seed_content.py --batch 1
    python seed_content.py --batch 1 --dry-run

Idempotent: applying a batch twice writes the same values.
"""
import argparse
import asyncio
import sys

from sqlalchemy import select

from app.database import async_session
from app.models.profile import Profile

# id: (display_name, occupation, headline, bio, looking_for)
BATCH_1 = {
    2: ("Rafael", "Port logistics director",
        "Grew up in Hialeah, still eat lunch there",
        "Thirty years moving freight through Port Miami and I still get a small thrill watching a ship come in. Divorced, two daughters in college, one very opinionated dog. I cook Sunday lunch for whoever shows up.",
        "Someone who tells me the truth even when it's inconvenient."),
    3: ("Tomás", "Marine mechanic",
        "I fix the boats you post photos on",
        "Coconut Grove, born and raised. I work with my hands and I'm better at it than most people are at anything. Weekends I'm usually on the water or asleep. I read more than people expect.",
        "Someone with their own thing going on who still makes time."),
    4: ("Dev", "Cardiologist",
        "Long shifts, short patience for small talk",
        "I moved here from Chicago for the weather and stayed for everything else. Baptist Health most days. I run at 5am not because I'm disciplined but because it's the only hour nobody needs me.",
        "Real conversation. I'd rather one good evening than five polite ones."),
    5: ("Camila", "Physical therapist",
        "Brickell, but I miss Bogotá constantly",
        "I put people back together after surgery, which means I'm patient and slightly bossy. I dance badly and enthusiastically. My friends call me when something breaks, emotionally or otherwise.",
        "Someone kind who's also funny. The order matters."),
    6: ("Marisol", "Owns three restaurants",
        "I feed people for a living and love for a hobby",
        "Twenty-two years in Miami kitchens, the last nine running my own. Widowed four years. My kids are grown and mildly horrified I'm dating. I'm up at four and asleep by nine, which narrows the field.",
        "Someone who's built something too and doesn't need me to explain why I work this hard."),
    7: ("Yaz", "Set designer",
        "I build the rooms you see in commercials",
        "Wynwood studio, too many houseplants. I'm Cuban on my mother's side and it's the loud half. I like early mornings, bad horror films, and being convinced of things I initially disagreed with.",
        "Curiosity. If you have a subject you can't shut up about, I want to hear it."),
    8: ("Warren", "Commercial real estate",
        "Fifty-two and finally comfortable saying what I want",
        "I develop mixed-use in the Design District. Two failed marriages taught me I'm not easy, just honest about it now. I collect records and I'm insufferable about it. Ask me anything.",
        "Someone direct. I've run out of appetite for guessing."),
    9: ("Andrés", "Grad student, marine biology",
        "I count fish for science and it's better than it sounds",
        "Twenty-three, at RSMAS, broke in the specific way that graduate students are. I dive four days a week. I can talk about coral until people leave the room and I've made peace with that.",
        "Someone who finds enthusiasm attractive rather than exhausting."),
    10: ("Peter", "Retired airline captain",
        "Thirty years of takeoffs, now I mostly garden",
        "Flew widebodies out of MIA until 2023. Now I grow mangoes badly and travel for pleasure instead of pay. Two grown sons, one grandchild, plenty of time and finally no schedule.",
        "Company. Someone to eat dinner with who has stories of their own."),
    11: ("Kofi", "Sound engineer",
        "I mix records in a room with no windows",
        "Little Haiti studio. I work nights, which ruins most social lives but suits mine. Ghanaian family, Miami accent. I'm calmer than my job suggests and I hold a grudge about very few things.",
        "Someone patient with odd hours who has their own life during the day."),
    12: ("Lucía", "Immigration attorney",
        "I argue for a living and try not to at home",
        "Twelve years of asylum work. It's heavy and I love it. Divorced, no kids by choice. I need someone who doesn't flinch when I talk about my day, or who knows when to change the subject.",
        "Steadiness. Somebody whose mood I don't have to manage."),
    13: ("Bea", "Pastry chef",
        "Awake at 3am, asleep by 8pm, sorry",
        "I run the bakery program at a hotel on the beach. Brazilian, though I've been here longer than there now. My schedule is antisocial and my croissants are excellent. I think it's a fair trade.",
        "Someone with early mornings of their own, or the patience for mine."),
    14: ("Elias", "Architect",
        "I design buildings I mostly can't afford to live in",
        "Thirty-four, my own small practice, three people and a lot of coffee. I sketch constantly. I'm told I'm quiet until I'm suddenly not. I'd rather walk a neighbourhood than sit in a restaurant.",
        "Someone who likes walking and doesn't need every silence filled."),
    15: ("Junior", "Personal trainer",
        "Yes, I'm the cliché. I'm also good at it.",
        "Twenty-five, South Beach, I train people who are serious and a few who aren't. I read philosophy on the bus, which nobody believes. I'm cheerful in a way that annoys my friends.",
        "Someone who takes something seriously. Doesn't matter what."),
    16: ("Renata", "Dermatologist",
        "Coral Gables, two cats, one ex-husband",
        "Forty-two and I like my life, which I'm told is intimidating. My practice keeps me busy and my friends keep me honest. I want company, not rescuing. I'm a very good cook and a terrible gardener.",
        "Someone secure enough that my life not needing fixing isn't a problem."),
    17: ("Naomi", "Fashion buyer",
        "I fly to Milan and see the inside of showrooms",
        "Twenty-eight, work sends me away a lot, which suits me. I'm from Kingston originally. I want someone who has plans when I'm gone rather than waiting. I'm blunt and I'll ask directly.",
        "Independence. Someone whose week isn't organised around mine."),
    18: ("Diane", "Sold her logistics company",
        "I worked very hard for a long time and then stopped",
        "Fifty-two. Sold the business in 2024 and I'm still learning what to do with a Tuesday. Divorced amicably. I sail, badly. I'd like to be surprised by someone at this stage rather than reassured.",
        "Someone interesting. I have enough comfort and not enough surprise."),
    19: ("Malik", "Line cook",
        "I work in a kitchen you've probably eaten in",
        "Twenty-six, Overtown, working my way up and it's slow. I'm ambitious in the boring way — showing up early. Days off I sleep and cook for my grandmother. I'm shy for about ten minutes.",
        "Someone who works hard too and gets why I'm tired on Sundays."),
    20: ("Julian", "Yacht brokerage",
        "I sell boats. It's less glamorous than it looks.",
        "Forty, divorced, one son who's twelve and funnier than me. Coconut Grove. I'm on the water constantly and genuinely never bored of it. I've stopped pretending to like clubs.",
        "Someone who'd rather be outside than out."),
    21: ("Sof", "Nursing student",
        "Twenty-two and permanently studying",
        "FIU, two years in, working at a coffee place to pay for it. I'm from Doral. I'm loud with my friends and quiet with everyone else until I'm not. I want to be a paediatric nurse.",
        "Someone patient. My schedule is a disaster for another two years."),
    22: ("Elaine", "Retired judge",
        "Thirty years on the bench, now reading for pleasure",
        "Fifty-three and recently retired, which everyone tells me was early. Widowed. I have strong opinions and I enjoy being argued with by someone who's done the reading. I walk five miles a day.",
        "Conversation. Genuinely, that's the whole list."),
    23: ("Priya", "Software engineer",
        "I work remote and forget to go outside",
        "Thirty-two, backend engineer, moved here from Austin for the winters. I'm quieter than most people in this city and I've made peace with that. I bake when stressed, so my colleagues eat well.",
        "Someone who doesn't think staying in is a wasted evening."),
    24: ("Hank", "Owns an HVAC company",
        "Not fancy. Built it from one van.",
        "Fifty-two, thirty-eight employees, started with a van and a loan from my uncle. Divorced a long time ago. I'm straightforward and I don't play games because I genuinely don't know how.",
        "Someone honest. I'd rather hear no than be managed."),
    25: ("Valentina", "Event producer",
        "I run the parties, I don't attend them",
        "Twenty-seven, I produce corporate events and weddings, which means I'm calm in a crisis and useless at relaxing. Venezuelan family, Kendall. My friends are my whole personality and I'm fine with it.",
        "Someone steady. My job is chaos and I don't want it at home."),
    26: ("Grace", "Hospital administrator",
        "I run a department and a household, badly, simultaneously",
        "Forty-five, two teenagers, one very demanding job at Jackson. Divorced three years and only now actually ready. I'm organised at work and a disaster at home. I laugh loudly.",
        "Someone patient with the fact that my kids come first, without resenting it."),
}

# Lengths vary on purpose from here. Real profiles aren't uniform — some
# people write a paragraph, some write six words — and equal-length bios are
# their own kind of tell.
BATCH_2 = {
    27: ("Isabela", "Veterinary nurse", "I smell faintly of dog and I've stopped apologising",
         "Twenty-six, Kendall, I work with animals because people are harder. Colombian family, Sunday lunches are non-negotiable.",
         "Someone gentle. It's underrated."),
    28: ("Marco", "Runs a construction firm", "Thirty-six and finally not working weekends",
         "Built the company from subcontracting. Six years in, forty guys. I'm proud of it and I try not to talk about it constantly.",
         "Someone with their own ambition so mine isn't the whole conversation."),
    29: ("Daniela", "Radiographer", "Nights at Mount Sinai, days asleep",
         "Thirty-five. Divorced, no kids. I've got a dry sense of humour that takes people a minute.",
         "Patience with my schedule and a decent sense of humour."),
    30: ("Sam", "Insurance brokerage", "Forty-four, two kids, one dog, no drama",
         "Aventura. My boys are nine and twelve and they're the best thing I've done. I coach their soccer badly.",
         "Someone who's fine coming second to my kids sometimes, without minding."),
    31: ("Cristian", "Bartender", "I make drinks and listen to strangers",
         "Twenty-three, South Beach. Saving for culinary school. I'm nocturnal and cheerful about it.",
         "Someone up late or willing to be occasionally."),
    32: ("Nadeem", "Anaesthesiologist", "I keep people asleep for a living",
         "Thirty-six, moved from Houston two years ago. Long hours, quiet outside them. I run and I read.",
         "Calm. My work is intense enough."),
    33: ("Ximena", "Graphic designer", "Freelance, which means always working",
         "Twenty-five, Little Havana. I design album covers and menus. Mexican, first generation.",
         "Someone creative or at least tolerant of it."),
    34: ("Gordon", "Private equity", "Forty-four, direct, occasionally too much so",
         "Brickell. Divorced. I work a lot and I'm honest that it won't change much. I ski and I read history.",
         "Someone who wants a real partner, not attention."),
    35: ("Alina", "Yoga instructor", "Not the serene kind, sorry",
         "Thirty-one, I teach six classes a week and swear more than you'd expect. Ukrainian, here since 2016.",
         "Someone grounded who won't ask me to be calmer."),
    36: ("Beto", "Restaurant group operations", "I open restaurants and rarely eat in them",
         "Forty-three, four locations. Cuban, Hialeah, the whole cliché and proud of it. Divorced, one daughter.",
         "Someone who eats late and doesn't mind hearing about margins."),
    37: ("Rosa", "Schoolteacher", "Fourth grade. Yes, really.",
         "Thirty-four, twelve years teaching, still love it. I'm patient professionally and less so personally.",
         "Kindness. That's genuinely the main thing."),
    38: ("Helena", "Owns a marketing agency", "Forty-four and I built the thing myself",
         "Twenty-two staff in Wynwood. Divorced, no kids, no regrets about either. I travel constantly for work and pleasure.",
         "Someone independent. I'm not looking to be someone's project or their manager."),
    39: ("Tati", "Physiotherapist", "Brazilian, Miami, still can't handle the cold",
         "Thirty-six. I fix athletes and weekend warriors. Loud, affectionate, terrible at hiding what I think.",
         "Warmth. I can't do reserved."),
    40: ("Barbara", "Retired paediatrician", "Fifty-five and finally sleeping properly",
         "Thirty years in medicine, retired last year. Widowed. Two grown daughters. I garden and I'm learning piano badly.",
         "Companionship. I've done the hard part of life and I'd like company for the rest."),
    41: ("Deshawn", "Music producer", "I make beats in a converted garage",
         "Twenty-six, Liberty City. It's going well enough to quit my day job, which I did last month, possibly early.",
         "Someone who believes in things before they're proven."),
    42: ("Claudia", "Corporate lawyer", "Thirty-seven, partner track, no free time",
         "I'm honest that work comes first right now, which is why this is hard. Argentinian. I run to stay sane.",
         "Someone busy too. Mutual understanding beats mutual availability."),
    43: ("Femi", "Data scientist", "I do maths for a bank and it's more fun than it sounds",
         "Thirty-four, Nigerian, moved here via London. I cook constantly and I'm competitive about board games.",
         "Someone curious. I'll happily explain anything and I like being explained to."),
    44: ("Trevor", "Hotel general manager", "I run a property on the beach",
         "Thirty-eight. Hospitality my whole career. I'm on call permanently, which has ended things before.",
         "Someone with a full life who won't resent my phone."),
    45: ("Jess", "Flight attendant", "Home four days a week if I'm lucky",
         "Thirty-five, based at MIA, mostly Latin America routes. I'm easy company and hard to pin down.",
         "Someone who won't take my schedule personally."),
    46: ("Andre", "Commercial pilot", "Forty-one, and yes, I hear it constantly",
         "Divorced, one son. When I'm home I'm properly home, which people underestimate.",
         "Someone secure with distance. It's the whole job."),
    47: ("Mimi", "Dental hygienist", "I judge your teeth. Sorry. It's automatic.",
         "Twenty-seven, Coral Gables. Cheerful, chatty, slightly too honest.",
         "Someone easygoing. I have enough intensity for two."),
    48: ("Rick", "Owns car dealerships", "Forty-one, three lots, one ex-wife",
         "Not glamorous but it works. I'm blunt and I don't do games. Two kids, teenagers, both smarter than me.",
         "Someone straightforward. I'm bad at subtext."),
    49: ("Omar", "Structural engineer", "I check that buildings stay up",
         "Thirty-four, Lebanese family, Miami my whole life. Quiet, dry, slow to warm up and then loyal.",
         "Someone patient with the first few weeks."),
    50: ("Paul", "Sold a software company", "Forty-one and figuring out what's next",
         "Exited in 2023, been travelling since, now back and slightly bored. Never married.",
         "Someone with momentum. I'm attracted to people who are going somewhere."),
    51: ("Jared", "Sports physiotherapist", "I work with a college team",
         "Thirty-two. Long seasons, quiet summers. I'm competitive about everything, which I'm told is exhausting.",
         "Someone who'll compete back."),
}

BATCH_3 = {
    52: ("Nicolas", "Import/export", "Forty-four years of moving things between countries",
         "Thirty-eight. Family business, Latin American trade. Divorced. I speak four languages and complain in all of them.",
         "Someone who travels or at least wants to."),
    53: ("Elif", "Interior designer", "I make other people's homes nice and neglect mine",
         "Thirty-six, Turkish, here eleven years. I'm particular about everything and self-aware about it.",
         "Someone with taste who won't defer to mine."),
    54: ("Bill", "Retired from oil trading", "Fifty-five, done working, not done living",
         "Retired early after a long stretch in energy. Divorced years ago. I fish, badly, and read constantly.",
         "Someone to travel with who has their own opinions about where."),
    55: ("Karina", "Nurse practitioner", "Thirty, primary care, permanently tired",
         "I look after a lot of people and I'd like someone to look after me occasionally.",
         "Someone who asks how my day was and waits for the answer."),
    56: ("Judith", "Owns a gallery", "Fifty-seven, Design District, forty years in art",
         "Widowed six years. I've stopped pretending I want to be alone. I'm opinionated and enjoy being challenged.",
         "Conversation and company. At this point I know exactly what I want."),
    57: ("Bianca", "Photographer", "I shoot weddings and hate weddings",
         "Twenty-six, Brazilian, Wynwood. Good at reading rooms, bad at small talk.",
         "Someone real. I've photographed enough performance."),
    58: ("Angela", "Runs a logistics firm", "Thirty-eight, built it with my brother",
         "Port work, unglamorous, profitable. Divorced. I'm direct and I don't have time to be otherwise.",
         "Someone who finds directness attractive rather than alarming."),
    59: ("Melina", "Makeup artist", "Editorial mostly, some film",
         "Thirty-seven, Greek family, Miami my whole life. I work odd hours with interesting people.",
         "Someone secure. My job involves a lot of beautiful strangers and it means nothing."),
    60: ("Curtis", "Owns a security company", "Fifty-three, ex-forces, still up at five",
         "Two hundred employees. Divorced a long time ago. I'm disciplined and trying to be less rigid about it.",
         "Someone warm. I could use it."),
    61: ("Lola", "Barista and art student", "Twenty-five, broke, happy",
         "New World School of the Arts. I paint large and live small. Puerto Rican, Miami born.",
         "Someone who takes art seriously without being precious."),
    62: ("Vikram", "Hospital consultant", "Thirty-nine, cardiology, Jackson",
         "Long hours, real satisfaction. Indian family, raised in Houston, here for the last six years.",
         "Someone with their own purpose. I don't want to be anyone's whole life."),
    63: ("Cami", "Dance teacher", "I teach kids salsa and it's the best job going",
         "Twenty-three, Little Havana, Cuban on both sides. Loud, warm, permanently moving.",
         "Someone who'll dance badly in public without complaining."),
    64: ("Suzanne", "Financial advisor", "Forty-two, I manage other people's money well",
         "Divorced, one teenager. I'm cautious professionally and impulsive personally, which confuses people.",
         "Someone stable who won't be intimidated by what I do."),
    65: ("Ana", "Sommelier", "I taste wine professionally and drink beer at home",
         "Thirty-five, Portuguese, here nine years. I work nights in a restaurant you've heard of.",
         "Someone who eats properly and doesn't rush it."),
    66: ("Michael", "Cosmetic dentist", "Forty-seven, Coral Gables, two practices",
         "Divorced, two kids at university. I golf badly and cook well. I'm at the stage of wanting one good thing.",
         "Someone genuine. I've had enough of surfaces."),
    67: ("Zoe", "Marine conservation", "I work on reefs and worry constantly",
         "Twenty-nine, NGO work, paid badly, wouldn't change it. Australian, here four years.",
         "Someone who cares about something bigger than themselves."),
    68: ("Farah", "Runs a PR firm", "Thirty-five, my own shop, six people",
         "Lebanese-American, Miami born. I talk for a living and I'm quiet at home. Divorced, no kids yet.",
         "Someone patient with a very full calendar."),
    69: ("Nate", "Firefighter", "Twenty-four on, forty-eight off",
         "Thirty-four, Miami-Dade Fire. The schedule is strange but it means real time off. Divorced.",
         "Someone who likes having me around for three days straight."),
    70: ("Denise", "Retired executive", "Forty-five and I stopped early on purpose",
         "Sold my share of a consultancy. Now I sit on two boards and have far too much free time.",
         "Someone with plans I can join rather than replace."),
    71: ("Julieta", "Speech therapist", "I work with kids who are finding their words",
         "Twenty-six, Venezuelan, Doral. Rewarding, exhausting, badly paid, worth it.",
         "Someone kind. It's the only requirement I actually hold to."),
    72: ("Damian", "Property developer", "Forty-one, I build things that last",
         "Small residential, mostly the Gables. Divorced. I'm calmer than I was at thirty.",
         "Someone settled. I've done the chaotic version."),
    73: ("Sara", "Occupational therapist", "Thirty, hospital work, sensible shoes",
         "I'm practical and unglamorous and genuinely happy. Cuban-American, Westchester.",
         "Someone unpretentious. Miami has enough of the other thing."),
    74: ("Leo", "Runs a bike shop", "Thirty-four, I sell bicycles and ride constantly",
         "Small shop in the Grove. Not making anyone rich but it's mine. Argentinian father, Miami mother.",
         "Someone who'd rather be outdoors."),
    75: ("Emilia", "Law student", "Twenty-four, UM, permanently in the library",
         "Second year. I'm ambitious and slightly insufferable about it. Colombian family, here since I was six.",
         "Someone who'll still be around after the bar exam."),
    76: ("Stephen", "Investment banking", "Forty, and yes, the hours are as bad as you've heard",
         "Brickell. Never married, which raises eyebrows at this point. I'm honest that I'm difficult to schedule.",
         "Someone with a full life of their own. I'd be a poor centrepiece."),
}

BATCH_4 = {
    77: ("Gabi", "Social worker", "Thirty, child services, heavy work",
         "I do a job most people couldn't. I'm cheerful anyway, which surprises people.",
         "Someone light. I get enough weight at work."),
    78: ("Patricia", "Owns a staffing agency", "Forty-seven, built it over eighteen years",
         "Divorced, two kids nearly grown. I'm blunt and I've stopped softening it for anyone.",
         "Someone who says what they mean the first time."),
    79: ("Nico", "Chef de partie", "Twenty-seven, working my way up a hot kitchen",
         "Long shifts, burns on both arms, love it completely. Peruvian father, Italian mother.",
         "Someone who eats late and asks about the food."),
    80: ("Antonio", "Freight forwarding", "Forty-four, family firm, third generation",
         "Cuban family, Hialeah. I work with my brothers, which is exactly as complicated as it sounds. Divorced.",
         "Someone with a big family or the patience for mine."),
    81: ("Tyler", "Real estate agent", "Twenty-seven, Brickell condos, commission only",
         "Good months and bad ones. I'm relentless and I know how that reads.",
         "Someone driven. I'd be bored otherwise."),
    82: ("Hassan", "Runs a car rental business", "Thirty-four, four locations, no days off",
         "Egyptian family, Miami born. I work constantly and I'm trying to stop.",
         "Someone who'll make me take a Sunday off."),
    83: ("Kenji", "UX designer", "Thirty-three, remote, quiet",
         "Japanese-American, moved from Seattle for the light. I'm introverted and completely fine with it.",
         "Someone who doesn't need constant plans."),
    84: ("Miriam", "Paediatric surgeon", "Forty-three, and the hours are brutal",
         "Divorced, no kids, which people find ironic. I'm intense at work and quiet outside it.",
         "Someone steady who won't need much reassurance."),
    85: ("Tania", "Hairdresser", "Thirty-one, my own chair, my own hours",
         "Wynwood salon. I hear everyone's problems all day, which makes me a good listener and a bad gossip.",
         "Someone who talks. I'm used to it."),
    86: ("Rachel", "Runs a nonprofit", "Forty-one, housing and homelessness",
         "Hard work, slow progress, worth every hour. Divorced. I'm optimistic in a way I have to work at.",
         "Someone who volunteers for something. Anything."),
    87: ("Paola", "Architect", "Thirty-four, residential, mostly renovations",
         "I fix other people's houses and live in a rental. Ecuadorian family, Miami my whole life.",
         "Someone visual. I notice everything and I'd like that shared."),
    88: ("Frank", "Retired from banking", "Fifty-two, out early, no regrets",
         "Thirty years in commercial lending, finished last year. Divorced twice, which taught me a great deal.",
         "Someone who's also learned something. I'm past pretending I haven't made mistakes."),
    89: ("Ricky", "Apprentice electrician", "Twenty-three, learning a trade, proud of it",
         "Two years in, three to go. My dad did the same. I'm cheerful and I'll fix anything you own.",
         "Someone who isn't snobbish about what I do."),
    90: ("Wesley", "Owns a printing business", "Forty-five, unglamorous, profitable",
         "Commercial print, twenty employees. Divorced, one daughter at college. I'm dependable to a fault.",
         "Someone who values reliability. It's my main quality."),
    91: ("Alexei", "Personal chef", "Thirty-one, I cook for four families",
         "Russian, here since I was twelve. Private work suits me — good money, strange hours, no restaurant chaos.",
         "Someone who'll eat what I make without commenting on the calories."),
    92: ("Marc", "Runs a dental lab", "Thirty-nine, technical work, quiet business",
         "Haitian family, Miami born. I make crowns and bridges. Precise, patient, boring in a way I've made peace with.",
         "Someone who finds steady attractive."),
    93: ("Renée", "Flight instructor", "Thirty, I teach people to fly small planes",
         "Opa-locka. Best job in the world on a clear morning. I'm calm under pressure and impatient in traffic.",
         "Someone adventurous. I'll take you up."),
    94: ("Douglas", "Retired lawyer", "Fifty-seven, thirty years litigating, done",
         "Widowed three years. Two grown sons. I read history, walk daily, and I'm learning to cook properly.",
         "Company and conversation. I've had enough silence."),
    95: ("Adriana", "Real estate broker", "Thirty-three, Gables and Grove",
         "Colombian, here since childhood. I work weekends and I'm honest about it up front.",
         "Someone who works Saturdays too, or understands why I do."),
    96: ("Ben", "Orthopaedic surgeon", "Forty-one, knees and shoulders",
         "Divorced, one son, joint custody. I cycle obsessively. I'm blunt in theatre and softer outside it.",
         "Someone who won't mistake bluntness for coldness."),
    97: ("Kat", "Journalist", "Thirty-five, local news, endlessly curious",
         "I ask questions for a living and can't switch it off. Fair warning.",
         "Someone with a story they haven't told everyone."),
    98: ("Rodrigo", "Runs a landscaping company", "Thirty-seven, I make gardens",
         "Twenty crews. Started cutting lawns at seventeen. Mexican family, first generation, immensely proud of it.",
         "Someone who appreciates something built slowly."),
    99: ("Ivan", "Sound designer for film", "Thirty-one, post-production, headphones on",
         "I make footsteps and rain. Ukrainian, here eight years. Quiet, funny once you know me.",
         "Someone patient with a quiet person."),
    100: ("Grant", "Owns a fleet business", "Thirty-seven, trucks, not exciting",
          "Fifty vehicles, unglamorous, good living. Never married. I'm plainspoken and slightly awkward.",
          "Someone who'll carry a conversation while I get comfortable."),
    101: ("Noor", "Pharmacist", "Thirty-five, and I know what everyone's taking",
          "Palestinian family, Miami born. Steady job, steady person. I read a lot and travel when I can.",
          "Someone calm and kind. That's genuinely the whole list."),
}

# Houston from here. Different city, different work: energy, the Medical
# Center, the port, NASA out at Clear Lake. Miami copy transplanted to Texas
# would read as wrong as the duplicate bios did.
BATCH_5 = {
    102: ("Ray", "Petroleum engineer", "Fifty-one, Energy Corridor, thirty years in",
          "Two grown kids, one ex-wife, one very good dog. I fish at Galveston most weekends and I'm not sorry about it.",
          "Someone easy to be quiet with."),
    103: ("Ify", "ICU nurse", "Thirty-seven, Texas Medical Center, night shifts",
          "Nigerian family, Houston born. I see hard things and I laugh a lot anyway.",
          "Someone warm who won't need me at 3am, because I'm at work."),
    104: ("Dale", "Owns a machine shop", "Fifty-one, oilfield parts, forty employees",
          "Started on the floor at nineteen. Divorced. I'm plainspoken and I fix things instead of discussing them.",
          "Someone patient with a man who's better with his hands than his words."),
    105: ("Trinh", "Dental practice owner", "Thirty-three, two locations in the Heights",
          "Vietnamese family, Alief. First in my family to go to university and they still mention it.",
          "Someone ambitious who understands family obligation."),
    106: ("Curtis", "Chemical plant manager", "Forty-seven, Baytown, shift work",
          "Divorced, two teenagers every other week. I barbecue seriously and I'm competitive about it.",
          "Someone who'll eat brisket and tell me the truth about it."),
    107: ("Jasmine", "Physician assistant", "Twenty-nine, cardiology, TMC",
          "Long days, good work. I'm from Sugar Land and I've barely left, which I'm fine with.",
          "Someone settled. I'm not looking for adventure, I'm looking for a person."),
    108: ("Glenn", "Retired from Shell", "Fifty-five, thirty-two years, done last spring",
          "Widowed two years. Two daughters, one grandson. I travel now and I'd rather not do it alone.",
          "Company. That's honestly it."),
    109: ("Rosa", "Restaurant manager", "Thirty-two, family place in the East End",
          "My parents opened it in 1994 and I run it now. Mexican family, Houston born. Sundays are for family.",
          "Someone who'll turn up to a loud family dinner and survive it."),
    110: ("Amir", "Cardiologist", "Forty-four, TMC, on call constantly",
          "Iranian family, raised in Katy. Divorced, no kids. I run and I read and I'm bad at relaxing.",
          "Someone who'll make me stop working occasionally."),
    111: ("Josh", "Land surveyor", "Thirty-two, outdoors most days",
          "I like the work and the weather half the year. Truck, dog, small house in the Heights.",
          "Someone uncomplicated. I'm suspicious of drama."),
    112: ("Andre", "Runs a logistics firm", "Thirty-six, port work, my own company",
          "Four years independent after eight working for someone else. It's finally comfortable.",
          "Someone who's built something too."),
    113: ("Nkechi", "Pharmacist", "Thirty-one, retail, and I'm tired of it",
          "Nigerian-American, Missouri City. Studying for a second qualification at night.",
          "Someone who'll be patient for two more years."),
    114: ("Bruce", "Owns an insurance agency", "Fifty-two, independent, twenty-two years",
          "Divorced a long time ago. Three grown kids. I coach little league and I take it too seriously.",
          "Someone kind. I've stopped looking for anything more complicated."),
    115: ("Ava", "Graduate student", "Twenty-five, public health at UT",
          "Second year of a doctorate, which was possibly a mistake. Broke and interested in everything.",
          "Someone curious. I'll happily talk until 2am."),
    116: ("Ken", "Retired NASA engineer", "Fifty-six, Clear Lake, thirty years",
          "Worked on things that went up. Widowed. I sail on the bay and I still get up early out of habit.",
          "Someone to sail with who doesn't mind that I'll explain the boat."),
    117: ("Priya", "Software engineer", "Twenty-five, remote, in my flat too much",
          "Indian family, Sugar Land. First job out of university, doing well, socially rusty.",
          "Someone who'll get me out of the house."),
    118: ("Marcus", "Owns a barbershop", "Thirty-nine, Third Ward, my own place",
          "Six chairs, eleven years. I know everybody's business and I keep it. Divorced, one son.",
          "Someone who'll come by and sit and talk while I work."),
    119: ("Chloe", "Veterinary surgeon", "Twenty-six, small animals, Montrose",
          "Newly qualified and permanently exhausted. I'm better with animals than people, working on it.",
          "Someone patient. I'm not great at this part."),
    120: ("Wes", "Commercial real estate", "Forty-eight, industrial, mostly warehouses",
          "Unglamorous and profitable. Divorced, two kids at college. I hunt and I read, in that order.",
          "Someone who doesn't need the city constantly."),
    121: ("Dominique", "Music teacher", "Thirty-three, high school band",
          "Fifth Ward, then Rice on a scholarship, then back to teach. It's the best decision I've made.",
          "Someone who cares about something the way I care about this."),
    122: ("Sanjay", "Runs a construction firm", "Thirty-seven, commercial build-out",
          "Indian family, Houston born. Sixty employees. I work too much and my mother tells me constantly.",
          "Someone who'll tell me to go home at a reasonable hour."),
    123: ("Tre", "Welder", "Twenty-five, pipeline work, good money",
          "Two weeks on, one off, which is hard on a social life. I'm saving to start something of my own.",
          "Someone independent who'll still be there when I get back."),
    124: ("Doug", "Owns car washes", "Fifty-two, eleven locations, boring and lucrative",
          "Divorced twice. I'm honest that I was the problem the first time. Grown kids, first grandchild.",
          "Someone who's also learned from getting it wrong."),
    125: ("Yolanda", "Social worker", "Thirty-five, hospital discharge planning",
          "I make sure people have somewhere to go. Heavy work. I'm from Acres Homes and still there.",
          "Someone who'll listen without trying to fix it."),
    126: ("Neil", "Anaesthetist", "Forty-one, TMC, unsociable hours",
          "Divorced, one daughter. I cycle long distances alone, which tells you something.",
          "Someone comfortable with their own company as well as mine."),
}

BATCH_6 = {
    127: ("Kim", "Interior designer", "Twenty-eight, residential, River Oaks mostly",
          "Korean-American, Spring Branch. I have excellent taste and a terrible flat.",
          "Someone who'll let me redo their living room eventually."),
    128: ("Stan", "Owns a trucking company", "Fifty-two, forty rigs, no glamour",
          "Started driving at twenty-two. Bought my first truck at thirty. Divorced. I'm up at four every day.",
          "Someone who understands early nights."),
    129: ("Bri", "Radiology technician", "Thirty-five, imaging, TMC",
          "Steady work, steady person. Divorced, one kid who's eight and hilarious.",
          "Someone good with children who isn't in a hurry to meet mine."),
    130: ("Walter", "Retired surgeon", "Fifty-two, general surgery, stopped early",
          "Burned out honestly rather than dramatically. Widowed. Now I teach two days a week and garden badly.",
          "Someone who won't be impressed by what I used to do."),
    131: ("Sade", "Runs a catering business", "Thirty-four, West African food",
          "Nigerian family. Started from my mother's kitchen, now three staff and a van. Very tired, very happy.",
          "Someone who eats properly and says what they think of the food."),
    132: ("Ron", "Retired refinery superintendent", "Fifty-seven, Texas City, thirty-four years",
          "Widowed. Two sons, both in the industry. I fish, I read westerns, I'm not complicated.",
          "Someone straightforward. I don't have the energy for guessing."),
    133: ("Michelle", "Occupational health nurse", "Thirty-four, corporate, regular hours for once",
          "Left hospital nursing for my sanity and I don't regret it. Divorced, no kids.",
          "Someone with a normal schedule. It's novel and I like it."),
    134: ("Tunde", "Petroleum geologist", "Forty-one, offshore rotations",
          "Nigerian, here fifteen years. Three weeks out, three weeks home, which is either perfect or impossible.",
          "Someone with a full life during my three weeks away."),
    135: ("Carlos", "Owns a body shop", "Thirty-five, collision repair, my own place",
          "Mexican family, Pasadena. Six years independent. My hands are permanently stained and I've stopped caring.",
          "Someone unpretentious."),
    136: ("Gary", "Runs an accountancy practice", "Forty-two, small business clients",
          "Divorced, two kids. I'm methodical and slightly dull and I've made peace with both.",
          "Someone who finds steady appealing rather than boring."),
    137: ("Adaeze", "Paediatric nurse", "Thirty-five, Texas Children's",
          "Best job in the world four days out of five. Nigerian family, Houston born.",
          "Someone patient. I use most of mine at work."),
    138: ("Terry", "Owns a plumbing company", "Fifty, thirty employees, on call always",
          "Started with a van at twenty-four. Divorced. Grown kids. I'm proud of the business and tired of running it.",
          "Someone to eventually retire with."),
    139: ("Layla", "Architecture student", "Twenty-five, final year, no sleep",
          "Rice. Lebanese family, Katy. I'm intense about work and easy about everything else.",
          "Someone who'll wait out my last year of studio."),
    140: ("Hank", "Ranch and property management", "Forty-three, land outside the city",
          "I look after other people's acreage. Divorced. I'm outdoors constantly and terrible at cities.",
          "Someone who'll come out to the country and not complain about the drive."),
    141: ("Grace", "Runs an events company", "Thirty-six, corporate, mostly energy sector",
          "Fifteen years of it. I'm calm during disasters and useless on holiday.",
          "Someone who'll teach me to relax properly."),
    142: ("Denise", "Owns a healthcare staffing firm", "Fifty-three, eighteen years, built alone",
          "Widowed four years. Two grown daughters. I'm direct, I'm busy, and I'm ready for company again.",
          "Someone confident. I run a company and I'd rather that wasn't a problem."),
    143: ("Emeka", "Mechanical engineer", "Thirty-one, plant design",
          "Nigerian, here since university. Quiet, precise, funnier than I look. I play football on Sundays.",
          "Someone who'll drag me out of my own head."),
    144: ("Brett", "Owns gyms", "Forty-one, three locations",
          "Not the shouty kind. Divorced, one son. I'm disciplined at work and disorganised everywhere else.",
          "Someone who'll keep me honest about balance."),
    145: ("Naya", "Physiotherapist", "Twenty-eight, sports clinic",
          "I work with athletes and weekend runners who think they're athletes. Both are fun.",
          "Someone active. It's most of my life."),
    146: ("Phil", "Energy trading", "Forty-seven, downtown, screens all day",
          "Divorced, two kids. High stress, decent money, not much left over some weeks.",
          "Someone patient with a hard job and an early bedtime."),
    147: ("Simone", "Runs a childcare centre", "Thirty-four, forty children, daily chaos",
          "I love it and it's completely exhausting. Divorced, no kids of my own yet, which people find odd.",
          "Someone calm. My days are loud enough."),
    148: ("Angela", "Retired schoolteacher", "Forty-nine, thirty years, out early",
          "Took the package and haven't looked back. Divorced. Two grown kids. I volunteer and I travel cheaply.",
          "Someone curious with time on their hands."),
    149: ("Diego", "Chef", "Thirty-two, Montrose, my own small place",
          "Twenty-six seats. Opened during a bad year and survived. Mexican father, Salvadoran mother.",
          "Someone who'll eat at the bar and keep me company on slow nights."),
    150: ("Kevin", "Owns an IT services firm", "Thirty-five, small business support",
          "Twelve staff. Not exciting, very steady. Never married, no particular reason.",
          "Someone who'll make plans, because I'm bad at it."),
    151: ("Zara", "Medical student", "Twenty-five, third year, permanently studying",
          "Baylor. Pakistani family, Sugar Land. Focused now, hopefully a person again by 2029.",
          "Someone independent who'll be around when I surface."),
}

BATCH_7 = {
    152: ("Owen", "Runs a solar installation firm", "Thirty-three, growing fast",
          "Four years in, twenty-two employees. Long hours, real belief in it. I'm on roofs more than I should be.",
          "Someone who'll be patient while I build this."),
    153: ("Malik", "Apprentice lineman", "Twenty-four, learning the trade",
          "Dangerous work, good money, proud of it. Fifth Ward. I'm saving hard.",
          "Someone practical who's building something too."),
    154: ("Randall", "Owns a supply company", "Forty-eight, industrial fasteners",
          "The least glamorous business in Texas and it pays for everything. Divorced, three kids.",
          "Someone who won't need me to be interesting at parties."),
    155: ("Tasha", "Dental hygienist", "Twenty-four, and yes I'll notice your teeth",
          "Acres Homes. Cheerful, chatty, close to my grandmother who raised me.",
          "Someone who gets on with family. It matters here."),
    156: ("Larry", "Retired from BP", "Fifty-three, took the early package",
          "Divorced. Two grown sons. I golf badly, I read constantly, and I've got far too much free time.",
          "Someone with plans I could join."),
    157: ("Bibi", "Nail technician", "Twenty-five, my own booth",
          "Vietnamese family, Alief. Building a client list and saving for my own place.",
          "Someone who takes me seriously. People underestimate this job."),
    158: ("Gerald", "Owns a landscaping business", "Fifty, commercial contracts",
          "Thirty employees. Started mowing at eighteen. Widowed six years and only now ready.",
          "Someone gentle. I'm out of practice at all this."),
    159: ("Josue", "Line cook", "Twenty-five, downtown hotel kitchen",
          "Working up. Honduran family, Gulfton. Long shifts and I still cook at home on days off.",
          "Someone who'll eat what I make and mean it when they say it's good."),
    160: ("Bill", "Retired air traffic controller", "Fifty-six, thirty years, finally quiet",
          "Widowed. The job aged me and I'd do it again. Now I fish and I'm learning guitar badly.",
          "Someone calm. I've had enough noise for one life."),
    161: ("Sean", "Paramedic", "Twenty-nine, twenty-four hour shifts",
          "Hard job, strange hours, wouldn't swap it. I'm calm in a crisis and messy the rest of the time.",
          "Someone steady who won't panic when I'm late."),
    162: ("Vernon", "Owns a scrap metal business", "Fifty-six, thirty years",
          "Unglamorous and it built everything I have. Divorced. Grown kids, two grandchildren.",
          "Someone practical who doesn't need impressing."),
    163: ("Amara", "HR director", "Thirty-five, energy company, downtown",
          "Nigerian-American. I handle other people's problems all day. Divorced, no kids.",
          "Someone with no drama at all. Genuinely none."),
    164: ("Wayne", "Owns a fabrication shop", "Fifty-four, custom metalwork",
          "Forty years with a welder in my hand. Divorced. I make furniture nobody asked for.",
          "Someone who appreciates things made properly."),
    165: ("Hugo", "Warehouse supervisor", "Thirty-two, port logistics",
          "Nights mostly. Honduran family, Houston born. Steady work, saving for a house.",
          "Someone building towards something too."),
    166: ("Frank", "Owns a pest control company", "Fifty-four, twenty-eight years",
          "Not the job I planned and it's been a good one. Divorced. Three grown kids, all doing better than me.",
          "Someone easy. I'm past complicated."),
    167: ("Lauren", "Speech pathologist", "Thirty, schools work",
          "I help kids find their words. Rewarding and badly paid. From Clear Lake, still there.",
          "Someone patient. It's the quality I value most."),
    168: ("Sylvia", "Retired hospital administrator", "Fifty, ran a department for years",
          "Took retirement early after my husband died. Two grown sons. I'm rebuilding a life and it's slow.",
          "Someone gentle who understands grief without dwelling in it."),
    169: ("Terrence", "Personal trainer", "Twenty-six, gym in Midtown",
          "I train people properly rather than shouting at them. Cheerful and possibly too energetic.",
          "Someone who'll come to the gym once and never again, and that's fine."),
    170: ("Charles", "Owns a printing business", "Forty-eight, commercial, thirty staff",
          "Second generation, took it from my father. Divorced. I read history and I fish badly.",
          "Someone with their own interests. I'm not much of an entertainer."),
    171: ("Deshawn", "Electrician", "Twenty-nine, residential, my own van",
          "Two years independent. Building a client list one job at a time. Sunnyside born.",
          "Someone who respects the grind."),
    172: ("Ravi", "Data engineer", "Thirty-five, energy analytics",
          "Indian family, Sugar Land. Remote most days, which is either great or isolating depending on the week.",
          "Someone who'll get me out of the house on a Wednesday."),
    173: ("Kelsey", "Vet nurse", "Thirty-one, emergency clinic",
          "Nights and weekends. I've seen everything. I'm unshockable and soft about animals.",
          "Someone who likes animals as much as I do, which is a high bar."),
    174: ("Marvin", "Owns a security firm", "Forty-nine, commercial contracts",
          "Ex-police, twenty years. Divorced. I'm watchful in a way that's hard to switch off.",
          "Someone who'll help me relax. I'm told I don't."),
    175: ("Jamal", "Graduate engineer", "Twenty-eight, oil services",
          "Two years in, learning fast. Houston born, Nigerian family. Ambitious and slightly impatient.",
          "Someone who's going somewhere too."),
    176: ("Steve", "Runs a car dealership", "Forty-seven, family business",
          "My father's, now mine. Divorced, two teenagers. I'm straightforward and I don't negotiate at home.",
          "Someone honest. I get enough negotiating at work."),
}

BATCH_8 = {
    177: ("Fola", "Investment analyst", "Thirty-four, downtown, long hours",
          "Nigerian-American, Houston born. Focused, tired, ready for something real.",
          "Someone with their own career who understands the hours."),
    178: ("Ted", "Owns a HVAC business", "Fifty-two, commercial contracts",
          "Twenty-five years. Divorced. I've built something solid and I'd like someone to enjoy it with.",
          "Someone easy-going. The business is stressful enough."),
    179: ("Camille", "Midwife", "Thirty, hospital deliveries",
          "Best job in the world at 4am when it goes right. From Beaumont, here eight years.",
          "Someone unshakeable. My hours are unpredictable and I can't change that."),
    180: ("Rick", "Owns a roofing company", "Forty-nine, storm work mostly",
          "Feast and famine. Divorced. Grown daughter I'm close to. I'm loud and I mean well.",
          "Someone who'll tell me to be quiet occasionally."),
    181: ("Dre", "Sound engineer", "Thirty-three, live venues",
          "Nights and weekends, which ends most relationships early. Third Ward. Worth it so far.",
          "Someone with their own nights out who'll occasionally come to mine."),
    182: ("Gene", "Retired pipeline inspector", "Fifty-one, thirty years on the road",
          "Divorced a long time ago, mostly my fault. Two sons I'm rebuilding things with. Home for good now.",
          "Someone forgiving of a man who got it wrong the first time."),
    183: ("Nia", "Marketing manager", "Twenty-seven, healthcare sector",
          "Houston born, Rice educated, still figuring it out. I'm ambitious and slightly anxious about it.",
          "Someone reassuring. I do enough worrying for two."),
    184: ("Omar", "Runs a wholesale food business", "Forty-one, restaurant supply",
          "Palestinian family, here since I was four. Up at three, done by two. Divorced, one son.",
          "Someone who'll have dinner at six because I'm asleep by nine."),
    185: ("Tyrell", "Diesel mechanic", "Twenty-four, fleet maintenance",
          "Good with engines, learning to be good with everything else. Saving for my own shop.",
          "Someone who'll be around for the long build."),
    186: ("Martin", "Owns storage facilities", "Forty-eight, six sites",
          "Deeply boring and it prints money. Divorced. I travel a lot now that I finally can.",
          "Someone to travel with. I'm tired of doing it alone."),
    187: ("Bisi", "Clinical researcher", "Thirty-six, TMC, oncology trials",
          "Nigerian, here twelve years. Serious work, serious person, decent sense of humour underneath.",
          "Someone who'll draw the lighter side out of me."),
    188: ("Chad", "Commercial diver", "Forty-two, offshore inspection",
          "Dangerous, well paid, three weeks on. Divorced. I'm calm because the job requires it.",
          "Someone independent. The rotation is non-negotiable."),
    189: ("Destiny", "Hairstylist", "Twenty-six, my own chair in the Heights",
          "Building a book one client at a time. Houston born. I'm ambitious and I talk constantly.",
          "Someone who listens well, because I don't stop."),
    190: ("Roger", "Retired from the port authority", "Fifty-six, thirty years on the ship channel",
          "Widowed three years. Two grown kids. I walk the bayou trails daily and I've read everything in the house.",
          "Company and conversation. I've been alone long enough."),
    191: ("Ines", "Translator", "Thirty-one, legal and medical, Spanish",
          "Freelance, which means feast or famine. Salvadoran family, Gulfton. Precise about language, relaxed about everything else.",
          "Someone who says what they mean. Occupational hazard."),
    192: ("Marlene", "Retired nurse manager", "Fifty-six, thirty-four years at TMC",
          "Widowed. Three grown children, four grandchildren. I've spent my life looking after people and I'd like a turn.",
          "Someone who'll look after me a little. I've earned it."),
    193: ("Kiara", "Elementary teacher", "Twenty-six, second grade",
          "Second year teaching and I still love it, which people say won't last. Sunnyside born and staying.",
          "Someone patient and kind. I'm around seven-year-olds all day and it's rubbed off."),
    194: ("Vince", "Owns a beverage distribution business", "Forty-seven, restaurants and bars",
          "Twenty years of it. Divorced. I know every restaurant in this city and I'll take you to the good ones.",
          "Someone who eats out and doesn't mind that I know the owner."),
    195: ("Ruth", "Occupational therapist", "Thirty-one, paediatrics",
          "Slow, careful work with children who need it. From Pearland. Quiet, steady, easily amused.",
          "Someone gentle. I don't have a high tolerance for noise."),
    196: ("Ed", "Owns a machine tooling firm", "Fifty-five, precision parts",
          "Aerospace and energy. Forty years, my own shop for twenty-five. Divorced. Grown kids, one grandchild.",
          "Someone steady. I'm not looking to be surprised, I'm looking to be comfortable."),
    197: ("Bao", "Optometrist", "Thirty-two, my own practice",
          "Vietnamese family, Alief. Opened two years ago and it's finally working. My parents are relieved.",
          "Someone who understands what it means to be the one who made it."),
    198: ("Kurt", "Runs a drilling services company", "Forty-eight, oilfield",
          "Cyclical business, thick skin required. Divorced twice. I'm honest that I'm hard work.",
          "Someone who knows their own mind and will say so."),
    199: ("Alani", "Nursing student", "Twenty-three, second year",
          "Working nights at a care home to pay for it. Exhausted and certain it's right.",
          "Someone who understands why I'm always studying."),
    200: ("Paul", "Owns a commercial cleaning firm", "Forty, ninety employees, night work",
          "Started with one contract and a mop. It's not glamorous and it's mine. Never married.",
          "Someone unimpressed by titles. I don't have one."),
    201: ("Tomi", "Physiotherapist", "Thirty-three, private clinic",
          "Nigerian-American, Houston born. I fix people slowly and I'm patient by training and temperament.",
          "Someone kind, funny, and around. That's the entire list."),
}

BATCHES = {
    1: BATCH_1, 2: BATCH_2, 3: BATCH_3, 4: BATCH_4,
    5: BATCH_5, 6: BATCH_6, 7: BATCH_7, 8: BATCH_8,
}


async def apply_batch(batch_no: int, dry_run: bool) -> int:
    content = BATCHES.get(batch_no)
    if not content:
        print(f"No batch {batch_no}. Available: {sorted(BATCHES)}")
        return 1

    async with async_session() as db:
        rows = (await db.execute(
            select(Profile).where(Profile.id.in_(list(content)))
        )).scalars().all()
        found = {p.id: p for p in rows}

        missing = set(content) - set(found)
        if missing:
            print(f"  warning: no profile for ids {sorted(missing)}")

        changed = 0
        for pid, (name, occupation, headline, bio, looking_for) in content.items():
            p = found.get(pid)
            if not p:
                continue
            if not p.is_seed:
                print(f"  SKIPPED {pid}: not a seed profile — refusing to overwrite a real member")
                continue
            p.display_name = name
            p.occupation = occupation
            p.headline = headline
            p.bio = bio
            p.looking_for = looking_for
            changed += 1
            if dry_run:
                print(f"  [dry-run] {pid}: {name} — {headline}")

        if dry_run:
            print(f"\n{changed} profiles would be updated. Nothing written.")
            await db.rollback()
        else:
            await db.commit()
            print(f"\n{changed} profiles updated.")
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--batch", type=int, required=True)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    sys.exit(asyncio.run(apply_batch(args.batch, args.dry_run)))
