"""add rich profile fields

Revision ID: 2e8a39bf2f64
Revises: a0b7058b9a8b
Create Date: 2026-06-06 11:35:14.720273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e8a39bf2f64'
down_revision: Union[str, None] = 'a0b7058b9a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('languages', sa.String(length=200), nullable=True))
    op.add_column('profiles', sa.Column('looking_for', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('offering', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('arrangement_types', postgresql.ARRAY(sa.String(length=50)), nullable=True))
    op.add_column('profiles', sa.Column('interests', postgresql.ARRAY(sa.String(length=50)), nullable=True))
    op.add_column('profiles', sa.Column('relationship_status', sa.Enum('SINGLE', 'DIVORCED', 'SEPARATED', 'WIDOWED', 'MARRIED', 'OPEN', name='relationshipstatus'), nullable=True))
    op.add_column('profiles', sa.Column('availability', sa.Enum('FLEXIBLE', 'WEEKDAYS', 'WEEKENDS', 'EVENINGS', 'TRAVEL_READY', name='availability'), nullable=True))
    op.add_column('profiles', sa.Column('ideal_first_date', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('is_income_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'is_income_verified')
    op.drop_column('profiles', 'ideal_first_date')
    op.drop_column('profiles', 'availability')
    op.drop_column('profiles', 'relationship_status')
    op.drop_column('profiles', 'interests')
    op.drop_column('profiles', 'arrangement_types')
    op.drop_column('profiles', 'offering')
    op.drop_column('profiles', 'looking_for')
    op.drop_column('profiles', 'languages')
    # ### end Alembic commands ###
